platform :ios, '12.4'
use_frameworks!
inhibit_all_warnings!

target 'ExampleApp' do
  project 'ExampleApp'
  pod "Screeb", "1.13.2"
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end
